server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hmall?&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    #    password: 123456
    database: 3
mybatis:
  configuration:
    map-underscore-to-camel-case: true